import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/scss/styles.scss";
import Header from "./header";

export const metadata: Metadata = {
   title: "Pinterest",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <Header/>
            {children}
         </body>
      </html>
   );
}
